version: "3.3"

services:
  mysql:
    image: mysql:5.7.28
    volumes:
      - ./docker/mysqldump/:/var/lib/mysql/
    container_name: mysql
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION" --max_allowed_packet=32M --collation-server=utf8_general_ci --character_set_server=utf8
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ./src:/home/app/api/src
      - ./logs:/home/app/api/logs
    container_name: api
    env_file: .env
    ports:
      - 3001:3000
    command: sh -c "/wait && yarn start:dev"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - mysql
