FROM node:14.17.5-alpine

ENV HOME=/home/app

COPY . $HOME/api/

WORKDIR $HOME/api

RUN yarn install && yarn build

# Add docker-compose-wait tool -------------------
ENV WAIT_VERSION 2.7.2

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait

RUN chmod +x /wait
